"""Pure portfolio-construction numerics.

Every function here is a function of arrays: no I/O, no configuration lookup,
no global state. Missing data is NaN throughout and is never silently filled.
"""

from weightcraft.align import AlignedStack, align
from weightcraft.arrays import (
    BoolMatrix,
    Cube,
    Dates,
    IntVector,
    Matrix,
    Vector,
)
from weightcraft.band import no_trade_band
from weightcraft.combine import (
    nanmean_stack,
    nanmedian_stack,
    normalised_shares,
    weighted_nanmean_stack,
    weighted_nanmean_stack_over_time,
)
from weightcraft.costs import apply_costs, book_returns, lagged, turnover
from weightcraft.cross_section import (
    project_out_rows,
    residualize_rows,
    row_counts,
    row_rank_pct,
    standardize_rows,
    top_n_mask,
)
from weightcraft.frame import DATE_COLUMN, WeightFrame
from weightcraft.metrics import (
    DEGENERATE_SHARPE,
    beta,
    cagr,
    compounded,
    drawdown,
    max_drawdown,
    sharpe,
    to_prices,
)
from weightcraft.normalize import (
    capped,
    center,
    clip_allocation,
    exposure_scale,
    fill_missing,
    gross,
    held,
    net,
    normalised_share,
    quantize,
    rescaled_to_held_count,
    row_sums,
    tilt,
    to_gross,
    weights_from_bins,
)
from weightcraft.risk import (
    EqualRiskConfig,
    VolatilityTargetConfig,
    downside_deviation,
    equal_risk_row,
    equal_risk_weights,
    inverse_volatility_share,
    observed_covariance,
    penalised_for_coverage,
    rolling_sums,
    stack_volatility,
    trailing_std,
    volatility_target,
)
from weightcraft.smoothing import ewm_mean, lag_rows, rolling_mean

__all__ = [
    "DATE_COLUMN",
    "DEGENERATE_SHARPE",
    "AlignedStack",
    "BoolMatrix",
    "Cube",
    "Dates",
    "EqualRiskConfig",
    "IntVector",
    "Matrix",
    "Vector",
    "VolatilityTargetConfig",
    "WeightFrame",
    "align",
    "apply_costs",
    "beta",
    "book_returns",
    "cagr",
    "capped",
    "center",
    "clip_allocation",
    "compounded",
    "downside_deviation",
    "drawdown",
    "equal_risk_row",
    "equal_risk_weights",
    "ewm_mean",
    "exposure_scale",
    "fill_missing",
    "gross",
    "held",
    "inverse_volatility_share",
    "lag_rows",
    "lagged",
    "max_drawdown",
    "nanmean_stack",
    "nanmedian_stack",
    "net",
    "no_trade_band",
    "normalised_share",
    "normalised_shares",
    "observed_covariance",
    "penalised_for_coverage",
    "project_out_rows",
    "quantize",
    "rescaled_to_held_count",
    "residualize_rows",
    "rolling_mean",
    "rolling_sums",
    "row_counts",
    "row_rank_pct",
    "row_sums",
    "sharpe",
    "stack_volatility",
    "standardize_rows",
    "tilt",
    "to_gross",
    "to_prices",
    "top_n_mask",
    "trailing_std",
    "turnover",
    "volatility_target",
    "weighted_nanmean_stack",
    "weighted_nanmean_stack_over_time",
    "weights_from_bins",
]
